    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (144, 'Afganistán');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (114, 'Albania');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (18, 'Alemania');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (98, 'Algeria');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (145, 'Andorra');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (119, 'Angola');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (4, 'Anguilla');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (147, 'Antigua y Barbuda');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (207, 'Antillas Holandesas');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (91, 'Arabia Saudita');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (5, 'Argentina');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (6, 'Armenia');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (142, 'Aruba');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (1, 'Australia');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (2, 'Austria');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (3, 'Azerbaiyán');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (80, 'Bahamas');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (127, 'Bahrein');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (149, 'Bangladesh');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (128, 'Barbados');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (9, 'Bélgica');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (8, 'Belice');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (151, 'Benín');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (10, 'Bermudas');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (7, 'Bielorrusia');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (123, 'Bolivia');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (79, 'Bosnia y Herzegovina');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (100, 'Botsuana');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (12, 'Brasil');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (155, 'Brunéi');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (11, 'Bulgaria');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (156, 'Burkina Faso');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (157, 'Burundi');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (152, 'Bután');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (159, 'Cabo Verde');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (158, 'Camboya');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (31, 'Camerún');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (32, 'Canadá');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (130, 'Chad');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (81, 'Chile');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (35, 'China');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (33, 'Chipre');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (82, 'Colombia');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (164, 'Comores');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (112, 'Congo (Brazzaville)');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (165, 'Congo (Kinshasa)');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (166, 'Cook, Islas');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (84, 'Corea del Norte');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (69, 'Corea del Sur');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (168, 'Costa de Marfil');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (36, 'Costa Rica');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (385, 'Croacia');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (113, 'Cuba');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (22, 'Dinamarca');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (169, 'Djibouti, Yibuti');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (103, 'Ecuador');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (23, 'Egipto');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (503, 'El Salvador');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (93, 'Emiratos Árabes Unidos');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (173, 'Eritrea');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (52, 'Eslovaquia');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (53, 'Eslovenia');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (28, 'España');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (55, 'Estados Unidos');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (68, 'Estonia');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (121, 'Etiopía');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (175, 'Feroe, Islas');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (90, 'Filipinas');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (63, 'Finlandia');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (176, 'Fiyi');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (64, 'Francia');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (180, 'Gabón');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (181, 'Gambia');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (21, 'Georgia');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (105, 'Ghana');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (143, 'Gibraltar');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (184, 'Granada');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (20, 'Grecia');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (94, 'Groenlandia');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (17, 'Guadalupe');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (185, 'Guatemala');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (186, 'Guernsey');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (187, 'Guinea');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (172, 'Guinea Ecuatorial');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (188, 'Guinea-Bissau');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (189, 'Guyana');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (16, 'Haiti');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (137, 'Honduras');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (73, 'Hong Kong');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (14, 'Hungría');
    INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (25, 'India');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (74, 'Indonesia');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (140, 'Irak');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (26, 'Irán');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (27, 'Irlanda');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (215, 'Isla Pitcairn');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (83, 'Islandia');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (228, 'Islas Salomón');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (58, 'Islas Turcas y Caicos');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (154, 'Islas Virgenes Británicas');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (24, 'Israel');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (29, 'Italia');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (132, 'Jamaica');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (70, 'Japón');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (193, 'Jersey');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (75, 'Jordania');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (30, 'Kazajstán');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (97, 'Kenia');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (34, 'Kirguistán');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (195, 'Kiribati');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (37, 'Kuwait');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (196, 'Laos');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (197, 'Lesotho');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (38, 'Letonia');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (99, 'Líbano');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (198, 'Liberia');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (39, 'Libia');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (126, 'Liechtenstein');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (40, 'Lituania');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (41, 'Luxemburgo');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (85, 'Macedonia');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (134, 'Madagascar');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (76, 'Malasia');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (125, 'Malawi');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (200, 'Maldivas');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (133, 'Malí');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (86, 'Malta');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (131, 'Man, Isla de');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (104, 'Marruecos');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (201, 'Martinica');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (202, 'Mauricio');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (108, 'Mauritania');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (42, 'México');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (43, 'Moldavia');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (44, 'Mónaco');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (139, 'Mongolia');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (117, 'Mozambique');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (205, 'Myanmar');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (102, 'Namibia');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (206, 'Nauru');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (107, 'Nepal');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (209, 'Nicaragua');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (210, 'Níger');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (115, 'Nigeria');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (212, 'Norfolk Island');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (46, 'Noruega');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (208, 'Nueva Caledonia');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (45, 'Nueva Zelanda');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (213, 'Omán');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (19, 'Países Bajos, Holanda');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (87, 'Pakistán');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (124, 'Panamá');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (88, 'Papúa-Nueva Guinea');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (110, 'Paraguay');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (89, 'Perú');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (178, 'Polinesia Francesa');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (47, 'Polonia');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (48, 'Portugal');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (246, 'Puerto Rico');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (216, 'Qatar');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (13, 'Reino Unido');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (65, 'República Checa');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (138, 'República Dominicana');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (49, 'Reunión');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (217, 'Ruanda');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (72, 'Rumanía');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (50, 'Rusia');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (242, 'Sáhara Occidental');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (223, 'Samoa');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (219, 'San Cristobal y Nevis');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (224, 'San Marino');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (221, 'San Pedro y Miquelón');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (225, 'San Vicente y las Granadinas');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (218, 'Santa Helena');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (222, 'Santa Lucia');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (220, 'Santo Tomé y Príncipe');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (141, 'Senegal');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (51, 'Serbia y Montenegro');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (226, 'Seychelles');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (227, 'Sierra Leona');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (71, 'Singapur');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (963, 'Siria');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (600, 'Somalia');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (54, 'Sri Lanka');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (247, 'Sudáfrica');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (605, 'Sudán');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (167, 'Suecia');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (55, 'Suiza');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (56, 'Surinam');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (230, 'Tailandia');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (234, 'Tanzania');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (143, 'Tayikistán');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (122, 'Togo');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (57, 'Tonga');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (59, 'Trinidad y Tobago');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (232, 'Tunez');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (60, 'Turkmenistán');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (61, 'Turquía');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (235, 'Tuvalu');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (236, 'Ucrania');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (90, 'Uganda');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (63, 'Uruguay');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (236, 'Uzbekistán');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (91, 'Vanuatu');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (10, 'Venezuela');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (135, 'Vietnam');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (180, 'Wallis y Futuna');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (241, 'Yemen');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (69, 'Yugoslavia');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (111, 'Zaire');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (92, 'Zambia');
	INSERT INTO artesanias_lumar.pais (pai_id, pai_nombre) VALUES (93, 'Zimbawe');
	